[config]
# ...

[templates.hyprland]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/colors.css'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/kitty-colors.conf'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.gtk3]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/gtk-colors.css'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/gtk-4.0/colors.css'

[templates.color-scheme]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.rofi]
input_path = '~/Projects/myhyprland-rice/dotfiles/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/Projects/myhyprland-rice/dotfiles/.config/rofi/colors.rasi'